### ISSUE TITLE
OnBoard String Upper Case Test 

### ISSUE THREAD

**Issue by alperenekin** [VB10/flutter-architecture-template#11]
test("String Helper Upper Case", () {
    String text = " Helelo";
    text = stringHelper.toUpper(text);
    expect(text.contains(RegExp("[A-Z\s]+")), true);
  });

toUpper fonksiyonu çağrılmadığında da test geçiyor. RegExp sanırım string içinde uppercase var mı diye kontrol ediyor bu şekilde. Belki testte expecti elle vermek çözebilir daha iyi bir yöntem bulamadım :)

**Comment by VB10** [comment]
bu regexi extension yazaarak ortaklatirabiliriz devaminda sorun kalmayacaktir
