### ISSUE TITLE
lib\core\init\network\core.dio yazım yanlışı

### ISSUE THREAD

**Issue by AlptugYaman** [VB10/flutter-architecture-template#12]
lib\core\init\network\core.dio

35. satır
        final model = _responseParser<R>(parseModel, _responseParser);
yerine 
        final model = _responseParser<R>(parseModel, response.data);

olmalı.

Ayrıca 

```
[
    {
        "create_date": "2020-10-06 19:14:21",
        "is_read": false,
        "notification_data": {
            "photo_id": 284,
            "user_id": 7,
        },
        "notification_type": "photo_comment"
    },
   ...
]
```

tarzı içiçe modellerde _responseParser'ın kullanımı mümkün değil sanırım ya da ben beceremedim.

**Comment by VB10** [comment]
selam 35.satir icin cok haklisin fix cikalim ona, ic ice yapilardada yapabilirsin aslinda modeli dogru tanimalaman onemli ornek verecek olursam buna bakabilirsin. Kolay gelsin iyi calismalar
https://gist.github.com/VB10/03af867bb33b474dff6c092abffb582d
