### ISSUE TITLE
Singleton  yapılar

### ISSUE THREAD

**Issue by bartukaan** [VB10/flutter-architecture-template#24]
Hocam , benim bir sorum olacaktı.
Singleton yapılar için getIt kütüphanesini kullanarak yapmak daha clean code yazmak açısından daha faydalı olur muydu?
Bunu önerir misiniz yoksa kullanmamanızın özel bir nedeni var mı acaba?

**Comment by VB10** [comment]
selam misal diyelim ki user modelimiz var bunu singleton yapmak yerine dedigin gibi getit tarzi kullanbilriz ama zaten provider varken getiit ile depdency vermeyi dogru bulmiyorum ki provider icinde lazy kullanimda var bizim singletonlara gelicek olursak asinda dogrudan constnat siniflar yapmak yerine bir singleton obje yaratip color lar gibi belli basli seyleri oradan almak en temizi

**Comment by bartukaan** [comment]
Get_It aslında bir dependency injection çözümünden ziyade locator mantığıyla kullanıldığı için sanırım ben de tam oturmayan bazı noktalar var. Konuyla ilgili araştırma yaptığımda https://stackoverflow.com/questions/57169616/provider-vs-get-it şöyle bir paylaşıma rastladım, daha önce aldığım eğitimlerde provider ile getIt'in sürekli bir arada kullanıldığını gördüm ve bende kendi projelerimde bu şekilde kullanmaya başladım. Bu yanlış bir davranış mı aslında onu merak ediyorum eğer öyleyse kullanmaktan vazgeçmeyi denemeliyim sanırım. Beni bu konuyla ilgili aydınlatabilirseniz çok sevinirim, belki başka arkadaşlar da vardır hem onlar içinde bilgilendirici olur.

**Comment by VB10** [comment]
bence gereksız dedıgım gıbı dependecy ınejctıon katmanı olarak yapılıyor doğru yani burada işte x servisini bu katmanda yapıp ilgil yerlerde doğrudan kullanmayı sağlatıyor ama unutmamalıki bi injection projeye yapılıyor ve herden çağırıp kullanılabiliyor gibi yani çok büyük yanlış demek doğru bulmuyorum birisi çıkar yapar ama ben sadece ilk projemde kullandım ardından hiç hitiyacım olmadı provider her şeyi çözüyor benim yapılarımda

**Comment by bartukaan** [comment]
Anladım hocam çok teşekkürler ilginiz ve vakit ayırdığınız için.
