### ISSUE TITLE
Network Layer

### ISSUE THREAD

**Issue by behlsoft** [VB10/flutter-architecture-template#36]
Hi team 
In your API service class you are just checking if response is type of particular type (model) thn only return else null... so how can you show user exact error that what happen .. Example in login, user can put wrong OTP so we have to show "Invalid OTP" or may be user enter expired OTP so we need to show "OTP expired"
But in your case we cant show this. Or may be i am wrong ... please suggest a way am using Vexana 

`final response = await manager.send<LoginResponseModel, LoginResponseModel>(NetworkRoutes.LOGIN.rawValue,
        parseModel: LoginResponseModel(), method: RequestType.POST, data: model);

    if (response.data is LoginResponseModel) {
      return response.data;
    } else {
      return null;
    }`

**Comment by VB10** [comment]
hello @behlsoft, of course, you have many scenarios for error state so vexana give response.error options for u. For example you can use like this:
![image](https://user-images.githubusercontent.com/17102578/131342305-d09b7061-6d2a-41f3-80b4-cd74be64d89e.png)

- Other think: if you have a base error model for the backend side, you can add this json model in network request then you can access directly model form response.error.model:   
 response.error.model
![image](https://user-images.githubusercontent.com/17102578/131342674-fc5c836f-1827-42e4-a625-e073520c0d64.png)
