### ISSUE TITLE
How dispose will come in play?

### ISSUE THREAD

**Issue by behlsoft** [VB10/flutter-architecture-template#38]
am using baseview for my view ... init and setcontext is working fine ... how dispose will work?
i want to dispose my controllers (initialised in viewmodel) when i move to other screen.. how it is possible?

**Comment by behlsoft** [comment]
my actual condition is :- i have camera controller in my view model which i want to dispose as soon as user go back ...so where should i do that.. thanks for support!

**Comment by behlsoft** [comment]
Hey any update?

**Comment by behlsoft** [comment]
Still no response?

**Comment by VB10** [comment]
hello @behlsoft  base view has a dispose options, and you can call your dispose custom method from viewmodel and that's fine, for example:
 return BaseView<LoginViewModel>(
      builder: (context, value) {
        return buildScaffold(value);
      },
      model: LoginViewModel(AuthenticationService(networkManager)),
      dispose: (model) {
        model.customDispose();
      },

But you need some changes from base view and try to implement like this

class BaseView<T extends Store> extends StatefulWidget {
  final Widget Function(BuildContext context, T value) builder;
  final T model;
  final void Function(T model) onModelReady;
  final void Function(T model) dispose;
  final VoidCallback? onRefresh;

  const BaseView(
      {Key? key, required this.builder, required this.model, required this.onModelReady, this.dispose, this.onRefresh})
      : super(key: key);

  @override
  _BaseViewState<T> createState() => _BaseViewState<T>();
}

Now, you can able to everyting in dispose method. this method work both state and viewmodel;
