### ISSUE TITLE
İnternetin olmadığı durumda gösterilecek popup

### ISSUE THREAD

**Issue by mehmetozdd** [VB10/flutter-architecture-template#49]
İnternet olmadığı zaman gösterilecek popupı vexananın sağladığı NoNetwork ile çözmeye çalıştım fakat vexana_manager.dart kısmında context istediği için başaramadım contexte ulaşamıyorum.Nasıl yapacağımı bilen varsa yardım edebilirse teşekkür ederim

**Comment by VB10** [comment]
bunu vexanaya acarsan bir ayri bakalim @mehmetozdd
